package utils;

public enum TipoMensaje {
	CONECTAR, DESCONECTAR, LISTAR, DESCARGAR, DAR_LISTA_CLIENTES, DAR_LISTA_ARCHIVOS, CONFIRMAR_DESCARGAR, CONFIRMAR_CONECTAR, EMPEZAR_CONEXION_P2P,
	FALLO_CONEXION_P2P,  ENVIAR_DATOS_EMISOR, SOLICITAR_CONEXION_P2P, USUARIO_REPETIDO, ACTUALIZAR_ARCHIVOS;
}

